#!/usr/bin/env bash
# This script makes up a story based on /etc/passwd content

while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

