#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59 using a while loop

hour=0
while [ $hour -le 12 ]; do
  minute=1
  while [ $minute -le 59 ]; do
    printf "%02d:%02d\n" "$hour" "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done

