#!/usr/bin/env bash
# This script displays "Hour: H" and minutes 1 to 59 for each hour using while loops

hour=0
while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]; do
    echo "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done

